function th_len_fun = th_len_fit(in1)
%TH_LEN_FIT
%    TH_LEN_FUN = TH_LEN_FIT(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    06-Dec-2018 23:50:54

k1 = in1(1,:);
k2 = in1(2,:);
t2 = k1.^2;
t3 = k2.^2;
th_len_fun = k1.*1.749146293824398e-1+k2.*1.557552710853198-t2.*2.410468959254218e-1-t3.*1.077702524894385+k1.*k2.*1.368411408995902e-1+k1.*t2.*1.328370129318179e-1+k1.*t3.*8.722821167017645e-1-k2.*t2.*3.805122970495259e-1+k2.*t3.*4.179659754229099e-1-6.045609844013482e-2;
