function [p_hip,v_hip] = Joint2Hip(in1,in2,params)
%JOINT2HIP
%    [P_HIP,V_HIP] = JOINT2HIP(IN1,IN2,params)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    01-Nov-2018 16:20:20

%    in1 = [q1, q2, q3, q4, q5]'
%    in2 = [dq1, dq2, dq3, dq4, dq5]'

L_fem = params.L_fem;
L_tib = params.L_tib;

dq1L = in2(1,:);
dq2L = in2(2,:);
dq32L = in2(3,:);
q32L = in1(3,:);
q1L = in1(1,:);
q2L = in1(2,:);
t2 = q1L+q2L;
t3 = q32L+q1L+q2L;
t4 = cos(t2);
t5 = cos(t3);
t6 = L_fem.*t4;
t7 = L_tib.*t5;
t8 = t6+t7;
t9 = sin(t2);
t10 = sin(t3);
p_hip = [-L_fem.*t9-L_tib.*t10;-L_fem.*t4-L_tib.*t5];
if nargout > 1
    t11 = L_fem.*t9;
    t12 = L_tib.*t10;
    t13 = t11+t12;
    v_hip = [-dq1L.*t8-dq2L.*t8-L_tib.*dq32L.*t5;dq1L.*t13+dq2L.*t13+L_tib.*dq32L.*t10];
end
